### ISSUE TITLE
Kwargs in jnp.where are deprecated

### ISSUE THREAD

**Issue by oilyraisin** [adaptive-intelligent-robotics/QDax#178]
Can't use kwargs x and y, which are positional only for jax>=0.4.28. (or so my computer tells me)
e.g. 

jnp.where(array==array, x=True, y=False) 

should be

 jnp.where(array==array, True, False)

**Comment by Lookatator** [comment]
Thanks @oilyraisin for your comment, we'll take care of it very soon.
More generally, we are in the process of updating the code to make it compliant with the latest versions of JAX.

**Comment by Lookatator** [comment]
This has been solved in #187, will be merged in `main` very soon
