### ISSUE TITLE
Wrong `static_argnames` and Docstring for `_sample_in_masked_pareto_front`

### ISSUE THREAD

**Issue by Lookatator** [adaptive-intelligent-robotics/QDax#46]
The Docstring and `num_samples` in the `static_argnames` seem to be outdated for the `_sample_in_masked_pareto_front` function.

https://github.com/adaptive-intelligent-robotics/QDax/blob/bddacf1ff84b41a19a0443263ac80e312c10d5b9/qdax/core/containers/mome_repertoire.py#L49-L56

**Comment by felixchalumeau** [comment]
Indeed! Thanks for the catch!
