### ISSUE TITLE
PGAME Replay Buffer delete newest solutions

### ISSUE THREAD

**Issue by manon-but-yes** [adaptive-intelligent-robotics/QDax#71]
Hi :)

The current PGAME Replay Buffer is using [jax.lax.dynamic_update_slice](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.dynamic_update_slice.html) to add new transition to the replay buffer. 
However, this is not acting like a circular buffer, meaning that if a batch contain more transitions than the size remaining in the buffer, it would delete the more recent transitions instead of the oldest ones.

**Comment by felixchalumeau** [comment]
Hi!

Thanks for raising this issue!

Indeed, the current replay buffer, inspired by Brax's implementation, does not handle overflow correctly. 

We recently had a look at [Brax's replay buffer implementation](https://github.com/google/brax/blob/main/brax/training/replay_buffers.py#L114) and they recently spotted this issue as well and fixed it. I would suggest to use their new way to handle it. What do you think about it?

**Comment by felixchalumeau** [comment]
Fixed by #75
