### ISSUE TITLE
Adding tasks and default scoring functions

### ISSUE THREAD

**Issue by felixchalumeau** [adaptive-intelligent-robotics/QDax#79]
Let's add tasks to QDax (rastrigin, sphere, arm, etc...) and provide default scoring functions for them as well as for Brax environments.

**Comment by Lookatator** [comment]
TODOs left:
- [ ] updating tests
- [ ] remove type aliases such as `PlayStepFnType`
- [ ] slight update of the documentation

**Comment by felixchalumeau** [comment]
Closed by #73
